@echo off
cd /d C:\xampp\htdocs\Turismo\datos\municipios
set B=https://raw.githubusercontent.com/PhantomInsights/mexico-geojson/main/2023/states
curl -sL -o aguascalientes.geojson "%B%/Aguascalientes.json"
curl -sL -o baja-california.geojson "%B%/Baja%%20California.json"
curl -sL -o baja-california-sur.geojson "%B%/Baja%%20California%%20Sur.json"
curl -sL -o campeche.geojson "%B%/Campeche.json"
curl -sL -o chiapas.geojson "%B%/Chiapas.json"
curl -sL -o chihuahua.geojson "%B%/Chihuahua.json"
curl -sL -o ciudad-de-mexico.geojson "%B%/Ciudad%%20de%%20M%%C3%%A9xico.json"
curl -sL -o coahuila.geojson "%B%/Coahuila%%20de%%20Zaragoza.json"
curl -sL -o colima.geojson "%B%/Colima.json"
curl -sL -o durango.geojson "%B%/Durango.json"
curl -sL -o guanajuato.geojson "%B%/Guanajuato.json"
curl -sL -o guerrero.geojson "%B%/Guerrero.json"
curl -sL -o hidalgo.geojson "%B%/Hidalgo.json"
curl -sL -o jalisco.geojson "%B%/Jalisco.json"
curl -sL -o estado-de-mexico.geojson "%B%/M%%C3%%A9xico.json"
curl -sL -o michoacan.geojson "%B%/Michoac%%C3%%A1n%%20de%%20Ocampo.json"
curl -sL -o morelos.geojson "%B%/Morelos.json"
curl -sL -o nayarit.geojson "%B%/Nayarit.json"
curl -sL -o nuevo-leon.geojson "%B%/Nuevo%%20Le%%C3%%B3n.json"
curl -sL -o puebla.geojson "%B%/Puebla.json"
curl -sL -o queretaro.geojson "%B%/Quer%%C3%%A9taro.json"
curl -sL -o quintana-roo.geojson "%B%/Quintana%%20Roo.json"
curl -sL -o san-luis-potosi.geojson "%B%/San%%20Luis%%20Potos%%C3%%AD.json"
curl -sL -o sinaloa.geojson "%B%/Sinaloa.json"
curl -sL -o sonora.geojson "%B%/Sonora.json"
curl -sL -o tabasco.geojson "%B%/Tabasco.json"
curl -sL -o tamaulipas.geojson "%B%/Tamaulipas.json"
curl -sL -o tlaxcala.geojson "%B%/Tlaxcala.json"
curl -sL -o veracruz.geojson "%B%/Veracruz%%20de%%20Ignacio%%20de%%20la%%20Llave.json"
curl -sL -o yucatan.geojson "%B%/Yucat%%C3%%A1n.json"
curl -sL -o zacatecas.geojson "%B%/Zacatecas.json"
echo DESCARGA-TERMINADA
